package SpaceExplorer.Utilities;

public class StaticData {
	public static final String[] PLANET_PREFIXES = {
		"Alpha ",
        "Beta ",
        "Gamma ",
        "Delta ",
        "Epsilon ",
        "Zeta ",
        "Eta ",
        "Theta ",
        "Sigma ",
        "Omega ",
        "Lambda ",
        "New ",
        "Old "
    };
	
    public static final String[] PLANET_NAMES = {
        "Phobos",
        "Deimos",
        "Eridanus",
        "Ariadne",
        "Linus",
        "Lysithea",
        "Themisto",
        "Erinome",
        "Aitne",
        "Pasithee",
        "Arche",
        "Scylla",
        "Medusa",
        "Dionysus",
        "Dione",
        "Phoebe",
        "Telesto",
        "Ceres",
        "Ymir",
        "Atlas",
        "Tarvos",
        "Jarvis",
        "Thor",
        "Cirilla",
        "Skathi",
        "Thrymr",
        "Navi",
        "Aegir",
        "Reach",
        "Helios",
        "Pandora",
        "Greip",
        "Grep",
        "Vim",
        "Emacs",
        "Ariel",
        "Oberon",
        "Daedalus",
        "Proteus",
        "Iridius",
        "Nereid",
        "Triton",
        "Bjorn",
        "Bash",
        "Elpis",
        "Baldur",
        "Fenrir",
        "Ubuntu",
        "Mint",
        "Debian",
        "Solaris",
        "Raspbian",
        "Rasputin",
        "Charlemagne",
        "Termux",
        "Gnome",
        "Tango",
        "Django",
        "Mango",
        "Cupcake",
        "Donut",
        "Eclair",
        "Froyo",
        "Gingerbread",
        "Honeycomb",
        "Jellybean",
        "KitKat",
        "Lollipop",
        "Marshmallow",
        "Nougat",
        "Oreo",
        "Pie",
        "Fedora",
        "Centos",
        "Unix",
        "Linux",
        "Azure",
        "Amazon",
        "Hyperion",
        "Aphelion",
    };
    
    public static final String[] PLANET_SUFFIXES = {
        " I",
        " II",
        " III",
        " IV",
        " V",
        " VI",
        " VII",
        " VIII",
        " IX",
        " X",
        " XI",
        " XII",
        " XIII",
        " Minor",
        " Major"
    };
    
    public static final String[] OUTPOST_NAMES = {
    	"Omicron"
    };
    
    public static final String[] OUTPOST_SUFFIXES = {
    	" Station",
    	" City",
    	" Outpost",
    	" Town",
    	" Village"
    };
}
